[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bet-engine"
version = "1.0.0"
description = "Best Estimated Trajectory Reconstruction Engine"

[tool.setuptools.packages.find]
include = ["source*", "config*"]
exclude = ["data*", "tests*", "test*"]