# UNIVERSAL CONSTANTS & GEODESY
geodesy:
  a: 6378137.0
  e2: 0.00669437999
  omega_e: 0.00007292115
  g_e: 9.7803253359 # Local Gravity
  k: 0.001931852652
  p0_isa: 101325.0
  t0_isa: 288.15
  l_isa: 0.0065

# INITIAL UNCERTAINTY MATRIX (P0)
initial_uncertainty:
  sigma_pos_m: 4.0
  sigma_vel_ms: 0.1
  sigma_theta_phi_deg: 0.05
  sigma_psi_deg: 5.0
  sigma_ba0_ms2: 0.02
  sigma_bg0_rads: 0.01

# SENSOR QUALITY INVARIANTS
sensor_quality:
  hdop_nominal: 1.2
  vdop_nominal: 1.5
  sigma_gnss_p_m: [2.500, 2.500, 4.000]
  sigma_gnss_v_ms: [0.050, 0.050, 0.100]
  sigma_baro_m: [0.000, 0.000, 1.500]
  sigma_mag_ut: [0.300, 0.300, 0.300]

# ALLAN VARIANCE STOCHASTIC PARAMETERS
allan_variance:
  vrw_noise_density: [3.305020e-04, 3.331339e-04, 3.313035e-04]
  accel_bias_instability: [1.319212e-04, 1.429060e-04, 1.459481e-04]
  accel_correlation_time_s: [28.231, 24.509, 24.509]
  arw_noise_density: [1.456168e-05, 1.455108e-05, 1.460147e-05]
  gyro_bias_instability: [4.410858e-06, 2.963894e-06, 4.568152e-06]
  gyro_correlation_time_s: [43.146, 3000.000, 43.146]

# GEOMETRIC CALIBRATION
calibration:
  r_arm_b_m: [1.20, 0.00, -0.35]
  s_a_ppm: [310.5, 290.2, 325.0] # X, Y, Z
  s_g_ppm: [345.1, 355.8, 330.4] # X, Y, Z
  m_a_deg: [0.05, -0.02, 0.03] # Coupled Missalignments in accelerometers: XY, XZ, YZ
  m_g_deg: [0.02, 0.01, -0.04] # Coupled Missalignments in gyros: XY, XZ, YZ
  m_hi_vec: [11.4, 21.4, 53.1] # Hard Iron (microTeslas)
  m_si_mat: # Soft Iron Matrix
    - [1.05, 0.02, -0.01]
    - [0.02, 0.95, 0.03]
    - [-0.01, 0.03, 1.02]

# SIGNAL PROCESSING
signal_processing:
  filter_cutoff_hz: 10.0
  filter_order: 4

# ALGORITHM TUNING
algorithm_tuning:
  k_innov_sigma: 50.0
  k_vib_mult: 4.0
  m_vib_window: 10

# VEHICLE DYNAMICS
vehicle:
  m_0_kg: 250.0
  m_f_kg: 100.0
  s_ref_m2: 0.07
  time_eng_off: 25